language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: U/uwGao6JsUWhMrMX4GsI01MgjeY5fooooSh21pxfMZX8koR804y/+UPJ2tkhipPZYXbqQJAqSsyONgIOPNQMd2Y1sxyFXy9vzgdj7CbtLq0o08boaNEQDeCehXe3cBw8Sz6YUsheemKqaeptUo3KTRL15BGrzyc0W2BV81Fa8voAyQW30oyHMXPNxbzrDeashnjkvSUx+lKPgraBdi5GkKvmIfCT9fPbMRJLFQ5ha+TZN9ZACBS5rt3UKic6VUOD4y1ZbUMw721kT6RpPVeWW1rY2g9ibltdAyTJhZ9JgB4q+rh5aWlA7E5PZfQ+8Iqc+r30BJfyscMErBN/K+jwqKnQt53JL+FYM4WlNz1H+aGXpePICn2fPNYxRw3dleyHqW7/Z3mLG0fx32j793ycTPcQFJfle/3/UIcvvka8VUakvRdYT4d9xTi3peED10+bXqWB3f3oTDbCIP7SVLDO9ZgFqb6KISXKUn3ipF+rElzPvzmsBA8oHDVEcsQ33zGS3PxhbOv8Q0aeExThjtzssYs2SuVoP+VZ2gBX1uLHsRjotdP/A7iqxTqQHQHcLob4uoDvRe7SdGPC0rcl5aUETyQW8MXD3t4rSh6zGO0c8cPIjGkraoDbKnakSi7pDclzAyloAedTWG4Z4bu0UhdiUEAscH70iUFrSUqaPeM7Xc=
  app: cise-s1-2020-team-22
